name: hero_premier
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons:
  flutter_svg:
  http:
  shared_preferences:
  provider:


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Levenim MT
      fonts:
        - asset: assets/fonts/lvnm.ttf
        - asset: assets/fonts/lvnmbd.ttf
          weight: 700
    - family: Hind Madurai
      fonts:
        - asset: assets/fonts/HindMadurai-Regular.ttf
        - asset: assets/fonts/HindMadurai-Bold.ttf
          weight: 700

