name: hero_premier
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^2.3.1
  cupertino_icons: ^0.1.3
  firebase_admob: ^0.9.3+4
  flutter_facebook_login: ^3.0.0
  flutter_html: ^1.0.0
  flutter_secure_storage: ^3.3.3
  flutter_svg: ^0.18.1
  fluttertoast: ^7.0.4
  http: ^0.12.2
  image_cropper: ^1.3.1
  image_picker: ^0.6.7+7
  json_annotation: ^3.0.1
  provider: ^4.3.2+1
  flutter_webview_plugin: ^0.3.11



dev_dependencies:
  build_runner: ^1.10.1
  json_serializable: ^3.4.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Levenim MT
      fonts:
        - asset: assets/fonts/lvnm.ttf
        - asset: assets/fonts/lvnmbd.ttf
          weight: 700
    - family: Hind Madurai
      fonts:
        - asset: assets/fonts/HindMadurai-Regular.ttf
        - asset: assets/fonts/HindMadurai-Bold.ttf
          weight: 700

